watchmelog/web/auth.py
from flask import Blueprint, request, abort, redirect, url_for, session
from requests_oauthlib import OAuth2Session

from watchmelog.config import app_config
from watchmelog.core.player import create_or_update_player, ensure_api_key_for_player
from watchmelog.models.state import SessionState


bp = Blueprint("auth", __name__)

_REGIONS = ["us", "eu", "apac"]

_BASE_AUTHORIZE_URI = "https://{region}.battle.net/oauth/authorize"
_BASE_TOKEN_URI = "https://{region}.battle.net/oauth/token"


@bp.route("/login")
def oauth_login_redirect():
    """
    Redirects a user to the specified Blizzard OAuth login page.
    """
    region = request.args.get("region", "").lower()

    if region not in _REGIONS:
        abort(400, f"Region must be one of {_REGIONS}")

    base_auth_url = _BASE_AUTHORIZE_URI.format(region=region)
    blizzard = OAuth2Session(
        app_config.oauth.client_id, redirect_uri=app_config.oauth.redirect_uri
    )
    auth_url, state = blizzard.authorization_url(base_auth_url)

    SessionState(state=state, region=region).save()

    return redirect(auth_url)


@bp.route("/register")
def oauth_registration_redirect():
    """
    Receives a code from Blizzard's OAuth login page after it has been
    filled by the user.
    """
    code = request.args["code"]
    state = request.args["state"]

    session_state: SessionState = SessionState.objects(state=state).first()
    blizzard = OAuth2Session(
        app_config.oauth.client_id,
        state=session_state.state,
        redirect_uri=app_config.oauth.redirect_uri,
    )
    token_url = _BASE_TOKEN_URI.format(region=session_state.region)

    token = blizzard.fetch_token(
        token_url,
        code=code,
        client_id=app_config.oauth.client_id,
        client_secret=app_config.oauth.client_secret,
    )
    player = create_or_update_player(token["access_token"], session_state.region)
    api_key = ensure_api_key_for_player(player)

    session["api_key"] = api_key.key

    session_state.delete()

    return redirect(url_for("root.root"))

watchmelog/templates/_formhelpers.jinja2
{% macro render_field(field) %}
    {% if field.type == 'MultiCheckboxField' %}
        <div class="inline fields">
            {{ field.label }}
            {% for subfield in field %}
                <div class="field">
                    <div class="ui checkbox">
                        {{ subfield }} {{ subfield.label }}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="field">
            {{ field.label }}
            {{ field(**kwargs)|safe }}
        </div>
    {% endif %}
    {% if field.errors %}
        <div class="ui error message">
            <div class="header">We had some issues</div>
            <ul class="list">
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                    </ul>
                    </div>
                {% endfor %}
    {% endif %}
{% endmacro %}

watchmelog/templates/base.jinja2
<html>
<head>
    <title>
        {% if page_title %}
            {{ page_title }} - WatchMeLog
        {% else %}
            WatchMeLog
        {% endif %}
    </title>
    <link rel="stylesheet" href="/static/vendor/sementic-ui/semantic.min.css"/>
</head>
<body class="pushable">
{% block content %}{% endblock %}
</body>
<script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
<script src="/static/vendor/sementic-ui/semantic.min.js"></script>
</html>

watchmelog/templates/index.jinja2
{% extends "base.jinja2" %}
{% set page_title = "Home" %}
{% block content %}

    <div class="pusher">
        <div class="ui inverted vertical masthead center aligned segment">
            <div class="ui container">
                <h1 class="ui inverted header">
                    WatchMeLog
                </h1>
                <h2>Login to start logging your Overwatch competitive matches.</h2>
                <a class="ui huge primary button" href="{{ url_for('auth.oauth_login_redirect') }}?region=us">
                    Login with Blizzard <i class="right arrow icon"></i>
                </a>
            </div>
        </div>
        <div class="ui vertical stripe segment">
            <div class="ui text container">
                {% if battletag %}
                    Logged in as: {{ battletag }}
                {% else %}
                    Not logged-in,
                    <a href="{{ url_for('auth.oauth_login_redirect') }}?region=us">login
                        here</a>.
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

watchmelog/templates/log_game.jinja2
{% extends "base.jinja2" %}
{% set page_title = "Log New Game" %}
{% block content %}

    <div class="ui raised very padded text container segment">
        <div class="pusher">
            {% from "_formhelpers.jinja2" import render_field %}
            <form class="ui {{ form_status_class(form) }} form" method="post">
                <div class="inline fields">
                    {{ render_field(form.sr) }}
                    {{ render_field(form.season) }}
                </div>
                {{ render_field(form.map) }}
                {{ render_field(form.heroes) }}
                <button class="ui button" type="submit">Submit</button>
            </form>
        </div>
    </div>


{% endblock %}